variable "location" {}
variable "environment" {}
variable "resource_group" {}
variable "address_space" {}
variable "subnet_internal_address_range" {}
variable "subnet_external_address_range" {}
variable "vnet_name" {}
variable "pip_name" {}
variable "lb_name" {}