variable "location" {}
variable "environment" {}
variable "resource_group" {}
variable "subnet_id" {}
variable "ssh_key_data" {}
variable "username" {}
variable "vm_name" {}
variable "lb_id" {}
variable "internal_backend_id" {}
variable "vnet_id" {}